---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cac-pipeline
  namespace: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: tekton
    pipeline-type: application-gitops
spec:
  description: |
    Configuration-as-Code Pipeline
    Applies AAP configuration using infra.aap_configuration collection
    Triggered by webhook from aap-config-as-code repository
  
  params:
    - name: git-url
      type: string
      description: URL of the aap-config-as-code repository
      default: https://github.com/djdanielsson/rh1-aap-config-as-code.git
    - name: git-revision
      type: string
      description: Git revision to apply (branch, tag, or commit)
      default: main
    - name: target-environment
      type: string
      description: Target AAP environment (dev, qa, prod)
  
  workspaces:
    - name: source
      description: Workspace for cloned repository
    - name: aap-credentials
      description: AAP API credentials for target environment
  
  results:
    - name: sync-status
      description: Status of configuration sync (success/failure)
      value: $(tasks.apply-config.results.status)
  
  tasks:
    - name: clone-cac-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: source
    
    - name: apply-config
      taskRef:
        name: ansible-playbook
      runAfter:
        - clone-cac-repo
      params:
        - name: playbook
          value: playbook.yml
        - name: inventory
          value: inventory.yml
        - name: target-environment
          value: $(params.target-environment)
      workspaces:
        - name: source
          workspace: source
        - name: aap-credentials
          workspace: aap-credentials
  
  finally:
    - name: notify-result
      params:
        - name: message
          value: "CaC Pipeline for $(params.target-environment) completed with status: $(tasks.apply-config.results.status)"
      taskSpec:
        params:
          - name: message
        steps:
          - name: log
            image: registry.access.redhat.com/ubi9/ubi-minimal:latest
            script: |
              #!/bin/bash
              echo "$(params.message)"

