---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: inner-loop-pipeline
  namespace: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: tekton
    pipeline-type: developer-feedback
spec:
  description: |
    Inner Loop Pipeline
    Provides rapid feedback to developers by testing changes in Dev AAP
    Target: <1 minute execution (Constitution PR-003)
  
  params:
    - name: git-url
      type: string
      description: URL of the automation repository
    - name: git-branch
      type: string
      description: Git branch to test
      default: main
    - name: project-name
      type: string
      description: AAP Project name to update
  
  workspaces:
    - name: aap-credentials
      description: Dev AAP API credentials
  
  results:
    - name: sync-status
      description: Project sync status
      value: $(tasks.trigger-sync.results.response)
  
  tasks:
    - name: update-project-branch
      taskRef:
        name: aap-api-call
      params:
        - name: aap-host
          value: "https://aap-dev-aap-dev.apps.cluster.example.com"  # Update with actual route
        - name: endpoint
          value: "/api/v2/projects/"
        - name: method
          value: "PATCH"
        - name: data
          value: '{"scm_branch": "$(params.git-branch)"}'
      workspaces:
        - name: aap-credentials
          workspace: aap-credentials
    
    - name: trigger-sync
      taskRef:
        name: aap-api-call
      runAfter:
        - update-project-branch
      params:
        - name: aap-host
          value: "https://aap-dev-aap-dev.apps.cluster.example.com"
        - name: endpoint
          value: "/api/v2/projects/$(params.project-name)/update/"
        - name: method
          value: "POST"
      workspaces:
        - name: aap-credentials
          workspace: aap-credentials
  
  finally:
    - name: feedback
      params:
        - name: status
          value: $(tasks.trigger-sync.status)
      taskSpec:
        params:
          - name: status
        steps:
          - name: log
            image: registry.access.redhat.com/ubi9/ubi-minimal:latest
            script: |
              #!/bin/bash
              if [ "$(params.status)" = "Succeeded" ]; then
                echo "✓ Dev AAP updated - check UI for job results"
              else
                echo "✗ Failed to update Dev AAP"
              fi

