---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-validation-pipeline
  namespace: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: tekton
    pipeline-type: quality-gate
spec:
  description: |
    PR Validation Pipeline
    Runs quality checks on pull requests: ansible-lint and molecule tests
    Blocks merge if checks fail (Constitution Article IV - Testing)
  
  params:
    - name: git-url
      type: string
      description: URL of the repository
    - name: git-revision
      type: string
      description: Git revision (PR commit SHA)
    - name: pr-number
      type: string
      description: Pull request number
  
  workspaces:
    - name: source
      description: Workspace for cloned repository
  
  results:
    - name: lint-status
      description: ansible-lint status (pass/fail)
      value: $(tasks.ansible-lint.status)
    - name: test-status
      description: molecule test status (pass/fail)
      value: $(tasks.molecule-test.status)
  
  tasks:
    - name: clone-pr
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: source
    
    - name: ansible-lint
      taskRef:
        name: ansible-lint
      runAfter:
        - clone-pr
      params:
        - name: path
          value: "."
      workspaces:
        - name: source
          workspace: source
    
    - name: molecule-test
      taskRef:
        name: molecule-test
      runAfter:
        - ansible-lint
      params:
        - name: role-path
          value: "roles"
        - name: scenario
          value: "default"
      workspaces:
        - name: source
          workspace: source
  
  finally:
    - name: report-status
      params:
        - name: pr-number
          value: $(params.pr-number)
        - name: lint-status
          value: $(tasks.ansible-lint.status)
        - name: test-status
          value: $(tasks.molecule-test.status)
      taskSpec:
        params:
          - name: pr-number
          - name: lint-status
          - name: test-status
        steps:
          - name: report
            image: registry.access.redhat.com/ubi9/ubi-minimal:latest
            script: |
              #!/bin/bash
              echo "PR #$(params.pr-number) Validation Results:"
              echo "  ansible-lint: $(params.lint-status)"
              echo "  molecule-test: $(params.test-status)"
              
              if [ "$(params.lint-status)" = "Succeeded" ] && [ "$(params.test-status)" = "Succeeded" ]; then
                echo "✓ All checks passed - PR ready for merge"
                exit 0
              else
                echo "✗ Some checks failed - PR blocked"
                exit 1
              fi

