---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: promotion-pipeline
  namespace: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: tekton
    pipeline-type: atomic-release
spec:
  description: |
    Atomic Promotion Pipeline
    Deploys version-locked release using Release Manifest
    Constitution Article III: Atomic Promotion
    Target: <5 minute execution (Constitution PR-004)
  
  params:
    - name: release-tag
      type: string
      description: Release manifest tag (e.g., v1.0.0)
    - name: target-environment
      type: string
      description: Target environment (qa or prod)
    - name: manifest-repo
      type: string
      description: Release manifest repository URL
      default: https://github.com/djdanielsson/rh1-release-manifest.git
  
  workspaces:
    - name: manifest-source
      description: Release manifest workspace
    - name: ee-source
      description: Execution environment source workspace
    - name: cac-source
      description: CaC source workspace
    - name: aap-credentials
      description: AAP API credentials for target environment
    - name: registry-credentials
      description: Image registry credentials
  
  results:
    - name: ee-image
      description: Built and pushed EE image reference
      value: $(tasks.push-ee.results.IMAGE_URL)
    - name: cac-status
      description: CaC application status
      value: $(tasks.apply-cac.results.status)
  
  tasks:
    # Step 1: Parse Release Manifest
    - name: clone-manifest
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.manifest-repo)
        - name: revision
          value: $(params.release-tag)
      workspaces:
        - name: output
          workspace: manifest-source
    
    - name: parse-manifest
      taskRef:
        name: manifest-parser
      runAfter:
        - clone-manifest
      params:
        - name: manifest-file
          value: "releases/release-$(params.release-tag).yml"
      workspaces:
        - name: manifest-source
          workspace: manifest-source
    
    # Step 2: Build Execution Environment
    - name: clone-ee-repo
      taskRef:
        name: git-clone
      runAfter:
        - parse-manifest
      params:
        - name: url
          value: https://github.com/djdanielsson/rh1-ee.git
        - name: revision
          value: $(tasks.parse-manifest.results.ee-commit)
      workspaces:
        - name: output
          workspace: ee-source
    
    - name: build-ee
      taskRef:
        name: buildah-build
      runAfter:
        - clone-ee-repo
      params:
        - name: image
          value: "web-ee:$(tasks.parse-manifest.results.version)"
        - name: context
          value: "."
      workspaces:
        - name: source
          workspace: ee-source
    
    - name: push-ee
      taskRef:
        name: buildah-push
      runAfter:
        - build-ee
      params:
        - name: image
          value: "web-ee:$(tasks.parse-manifest.results.version)"
        - name: registry
          value: "image-registry.openshift-image-registry.svc:5000/aap-$(params.target-environment)"
      workspaces:
        - name: dockerconfig
          workspace: registry-credentials
    
    # Step 3: Apply Configuration-as-Code
    - name: clone-cac-repo
      taskRef:
        name: git-clone
      runAfter:
        - parse-manifest
      params:
        - name: url
          value: https://github.com/djdanielsson/rh1-aap-config-as-code.git
        - name: revision
          value: $(tasks.parse-manifest.results.aap-cac-commit)
      workspaces:
        - name: output
          workspace: cac-source
    
    - name: apply-cac
      taskRef:
        name: ansible-playbook
      runAfter:
        - clone-cac-repo
        - push-ee  # Wait for EE to be available
      params:
        - name: playbook
          value: playbook.yml
        - name: inventory
          value: inventory.yml
        - name: target-environment
          value: "aap_$(params.target-environment)"
        - name: extra-vars
          value: '{"controller_execution_environments": [{"name": "Web EE", "image": "$(tasks.push-ee.results.IMAGE_URL)"}]}'
      workspaces:
        - name: source
          workspace: cac-source
        - name: aap-credentials
          workspace: aap-credentials
  
  finally:
    - name: promotion-result
      params:
        - name: release-tag
          value: $(params.release-tag)
        - name: target-env
          value: $(params.target-environment)
        - name: ee-image
          value: $(tasks.push-ee.results.IMAGE_URL)
        - name: cac-status
          value: $(tasks.apply-cac.results.status)
      taskSpec:
        params:
          - name: release-tag
          - name: target-env
          - name: ee-image
          - name: cac-status
        steps:
          - name: report
            image: registry.access.redhat.com/ubi9/ubi-minimal:latest
            script: |
              #!/bin/bash
              echo "========================================="
              echo "Atomic Promotion Result"
              echo "========================================="
              echo "Release: $(params.release-tag)"
              echo "Environment: $(params.target-env)"
              echo "EE Image: $(params.ee-image)"
              echo "CaC Status: $(params.cac-status)"
              echo "========================================="
              
              if [ "$(params.cac-status)" = "success" ]; then
                echo "✓ Promotion completed successfully"
                echo "Constitution Article III: Atomic promotion verified"
                exit 0
              else
                echo "✗ Promotion failed"
                echo "Rollback required: Re-run with previous release tag"
                exit 1
              fi

