apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: aap-operatorgroup
  namespace: aap-qa
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  targetNamespaces:
    - aap-qa

