---
# TriggerBinding for CaC Pipeline
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cac-triggerbinding
  namespace: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: tekton
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.after)  # Commit SHA
    - name: git-ref
      value: $(body.ref)    # Branch ref
---
# TriggerTemplate for CaC Pipeline
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cac-triggertemplate
  namespace: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: tekton
spec:
  params:
    - name: git-url
      description: Git repository URL
    - name: git-revision
      description: Git commit SHA
    - name: git-ref
      description: Git ref (branch)
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: cac-run-
        namespace: dev-tools
        labels:
          tekton.dev/pipeline: cac-pipeline
          trigger-type: webhook
      spec:
        serviceAccountName: tekton-cac-sa
        pipelineRef:
          name: cac-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: target-environment
            value: "dev"  # Auto-deploy to dev on main branch push
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: aap-credentials
            secret:
              secretName: aap-dev-api-credentials

