---
# EventListener for GitHub webhooks
# Listens for push events and PR events
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-webhook-listener
  namespace: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: tekton
    trigger-type: webhook
spec:
  serviceAccountName: tekton-cac-sa
  triggers:
    # Trigger 1: CaC Pipeline on push to aap-config-as-code repo
    - name: cac-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.repository.name == 'rh1-aap-config-as-code' && body.ref == 'refs/heads/main'"
      bindings:
        - ref: cac-triggerbinding
      template:
        ref: cac-triggertemplate
    
    # Trigger 2: PR Validation on pull_request events
    - name: pr-validation-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: pr-triggerbinding
      template:
        ref: pr-triggertemplate
    
    # Trigger 3: Promotion Pipeline on tag push to release-manifest repo
    - name: promotion-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.repository.name == 'rh1-release-manifest' && body.ref.startsWith('refs/tags/v')"
      bindings:
        - ref: promotion-triggerbinding
      template:
        ref: promotion-triggertemplate
---
# Expose EventListener via Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: github-webhook-listener
  namespace: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: tekton
    eventlistener: github-webhook-listener
spec:
  to:
    kind: Service
    name: el-github-webhook-listener
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

