---
# TriggerBinding for PR Validation Pipeline
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pr-triggerbinding
  namespace: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: tekton
spec:
  params:
    - name: git-url
      value: $(body.pull_request.head.repo.clone_url)
    - name: git-revision
      value: $(body.pull_request.head.sha)
    - name: pr-number
      value: $(body.pull_request.number)
---
# TriggerTemplate for PR Validation Pipeline
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pr-triggertemplate
  namespace: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: tekton
spec:
  params:
    - name: git-url
      description: Git repository URL
    - name: git-revision
      description: PR commit SHA
    - name: pr-number
      description: Pull request number
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pr-validation-
        namespace: dev-tools
        labels:
          tekton.dev/pipeline: pr-validation-pipeline
          trigger-type: webhook
          pr-number: $(tt.params.pr-number)
      spec:
        serviceAccountName: tekton-pr-sa
        pipelineRef:
          name: pr-validation-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: pr-number
            value: $(tt.params.pr-number)
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi

