---
# TriggerBinding for Promotion Pipeline
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: promotion-triggerbinding
  namespace: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: tekton
spec:
  params:
    - name: release-tag
      value: $(body.ref)  # refs/tags/v1.0.0
    - name: manifest-repo
      value: $(body.repository.clone_url)
---
# TriggerTemplate for Promotion Pipeline (QA)
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: promotion-triggertemplate
  namespace: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: tekton
spec:
  params:
    - name: release-tag
      description: Release tag (v1.0.0)
    - name: manifest-repo
      description: Release manifest repository URL
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: promotion-qa-
        namespace: dev-tools
        labels:
          tekton.dev/pipeline: promotion-pipeline
          trigger-type: webhook
          release-tag: $(tt.params.release-tag)
      spec:
        serviceAccountName: tekton-promotion-sa
        pipelineRef:
          name: promotion-pipeline
        params:
          - name: release-tag
            value: $(tt.params.release-tag)
          - name: target-environment
            value: "qa"  # Auto-promote to QA on tag
          - name: manifest-repo
            value: $(tt.params.manifest-repo)
        workspaces:
          - name: manifest-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: ee-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
          - name: cac-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: aap-credentials
            secret:
              secretName: aap-qa-api-credentials
          - name: registry-credentials
            emptyDir: {}  # Update with actual registry credentials secret if needed

