---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-tools
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    environment: shared
    app: tekton-pipelines
    managed-by: argocd

