---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  
  source:
    repoURL: https://github.com/djdanielsson/rh1-cluster-config.git
    targetRevision: main
    path: operators
  
  destination:
    server: https://kubernetes.default.svc
    # No namespace - resources specify their own namespaces
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # Namespaces created in wave -3
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
  
  # Ignore operator-managed fields
  ignoreDifferences:
    - group: operators.coreos.com
      kind: Subscription
      jsonPointers:
        - /status
    - group: operators.coreos.com
      kind: OperatorGroup
      jsonPointers:
        - /status

