---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-tasks
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  
  source:
    repoURL: https://github.com/djdanielsson/rh1-cluster-config.git
    targetRevision: main
    path: tekton/tasks
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-tools
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 2m

